export const countries = {
  AC: {
    code: "AC",
    unicode: "U+1F1E6 U+1F1E8",
    name: "Île de l'Ascension",
    emoji: "🇦🇨",
  },
  AD: {
    code: "AD",
    unicode: "U+1F1E6 U+1F1E9",
    name: "Andorre",
    emoji: "🇦🇩",
  },
  AE: {
    code: "AE",
    unicode: "U+1F1E6 U+1F1EA",
    name: "Émirats arabes unis",
    emoji: "🇦🇪",
  },
  AF: {
    code: "AF",
    unicode: "U+1F1E6 U+1F1EB",
    name: "Afghanistan",
    emoji: "🇦🇫",
  },
  AG: {
    code: "AG",
    unicode: "U+1F1E6 U+1F1EC",
    name: "Antigua-et-Barbuda",
    emoji: "🇦🇬",
  },
  AI: {
    code: "AI",
    unicode: "U+1F1E6 U+1F1EE",
    name: "Anguilla",
    emoji: "🇦🇮",
  },
  AL: {
    code: "AL",
    unicode: "U+1F1E6 U+1F1F1",
    name: "Albanie",
    emoji: "🇦🇱",
  },
  AM: {
    code: "AM",
    unicode: "U+1F1E6 U+1F1F2",
    name: "Arménie",
    emoji: "🇦🇲",
  },
  AO: {
    code: "AO",
    unicode: "U+1F1E6 U+1F1F4",
    name: "Angola",
    emoji: "🇦🇴",
  },
  AQ: {
    code: "AQ",
    unicode: "U+1F1E6 U+1F1F6",
    name: "Antarctique",
    emoji: "🇦🇶",
  },
  AR: {
    code: "AR",
    unicode: "U+1F1E6 U+1F1F7",
    name: "Argentine",
    emoji: "🇦🇷",
  },
  AS: {
    code: "AS",
    unicode: "U+1F1E6 U+1F1F8",
    name: "Samoa américaines",
    emoji: "🇦🇸",
  },
  AT: {
    code: "AT",
    unicode: "U+1F1E6 U+1F1F9",
    name: "Autriche",
    emoji: "🇦🇹",
  },
  AU: {
    code: "AU",
    unicode: "U+1F1E6 U+1F1FA",
    name: "Australie",
    emoji: "🇦🇺",
  },
  AW: {
    code: "AW",
    unicode: "U+1F1E6 U+1F1FC",
    name: "Aruba",
    emoji: "🇦🇼",
  },
  AX: {
    code: "AX",
    unicode: "U+1F1E6 U+1F1FD",
    name: "Îles Åland",
    emoji: "🇦🇽",
  },
  AZ: {
    code: "AZ",
    unicode: "U+1F1E6 U+1F1FF",
    name: "Azerbaïdjan",
    emoji: "🇦🇿",
  },
  BA: {
    code: "BA",
    unicode: "U+1F1E7 U+1F1E6",
    name: "Bosnie-Herzégovine",
    emoji: "🇧🇦",
  },
  BB: {
    code: "BB",
    unicode: "U+1F1E7 U+1F1E7",
    name: "Barbade",
    emoji: "🇧🇧",
  },
  BD: {
    code: "BD",
    unicode: "U+1F1E7 U+1F1E9",
    name: "Bangladesh",
    emoji: "🇧🇩",
  },
  BE: {
    code: "BE",
    unicode: "U+1F1E7 U+1F1EA",
    name: "Belgique",
    emoji: "🇧🇪",
  },
  BF: {
    code: "BF",
    unicode: "U+1F1E7 U+1F1EB",
    name: "Burkina Faso",
    emoji: "🇧🇫",
  },
  BG: {
    code: "BG",
    unicode: "U+1F1E7 U+1F1EC",
    name: "Bulgarie",
    emoji: "🇧🇬",
  },
  BH: {
    code: "BH",
    unicode: "U+1F1E7 U+1F1ED",
    name: "Bahreïn",
    emoji: "🇧🇭",
  },
  BI: {
    code: "BI",
    unicode: "U+1F1E7 U+1F1EE",
    name: "Burundi",
    emoji: "🇧🇮",
  },
  BJ: {
    code: "BJ",
    unicode: "U+1F1E7 U+1F1EF",
    name: "Bénin",
    emoji: "🇧🇯",
  },
  BL: {
    code: "BL",
    unicode: "U+1F1E7 U+1F1F1",
    name: "Saint-Barthélemy",
    emoji: "🇧🇱",
  },
  BM: {
    code: "BM",
    unicode: "U+1F1E7 U+1F1F2",
    name: "Bermudes",
    emoji: "🇧🇲",
  },
  BN: {
    code: "BN",
    unicode: "U+1F1E7 U+1F1F3",
    name: "Brunei",
    emoji: "🇧🇳",
  },
  BO: {
    code: "BO",
    unicode: "U+1F1E7 U+1F1F4",
    name: "Bolivie",
    emoji: "🇧🇴",
  },
  BQ: {
    code: "BQ",
    unicode: "U+1F1E7 U+1F1F6",
    name: "Pays-Bas caribéens",
    emoji: "🇧🇶",
  },
  BR: {
    code: "BR",
    unicode: "U+1F1E7 U+1F1F7",
    name: "Brésil",
    emoji: "🇧🇷",
  },
  BS: {
    code: "BS",
    unicode: "U+1F1E7 U+1F1F8",
    name: "Bahamas",
    emoji: "🇧🇸",
  },
  BT: {
    code: "BT",
    unicode: "U+1F1E7 U+1F1F9",
    name: "Bhoutan",
    emoji: "🇧🇹",
  },
  BV: {
    code: "BV",
    unicode: "U+1F1E7 U+1F1FB",
    name: "Île Bouvet",
    emoji: "🇧🇻",
  },
  BW: {
    code: "BW",
    unicode: "U+1F1E7 U+1F1FC",
    name: "Botswana",
    emoji: "🇧🇼",
  },
  BY: {
    code: "BY",
    unicode: "U+1F1E7 U+1F1FE",
    name: "Biélorussie",
    emoji: "🇧🇾",
  },
  BZ: {
    code: "BZ",
    unicode: "U+1F1E7 U+1F1FF",
    name: "Belize",
    emoji: "🇧🇿",
  },
  CA: {
    code: "CA",
    unicode: "U+1F1E8 U+1F1E6",
    name: "Canada",
    emoji: "🇨🇦",
  },
  CC: {
    code: "CC",
    unicode: "U+1F1E8 U+1F1E8",
    name: "Îles Cocos (Keeling)",
    emoji: "🇨🇨",
  },
  CD: {
    code: "CD",
    unicode: "U+1F1E8 U+1F1E9",
    name: "Congo - Kinshasa",
    emoji: "🇨🇩",
  },
  CF: {
    code: "CF",
    unicode: "U+1F1E8 U+1F1EB",
    name: "République centrafricaine",
    emoji: "🇨🇫",
  },
  CG: {
    code: "CG",
    unicode: "U+1F1E8 U+1F1EC",
    name: "Congo - Brazzaville",
    emoji: "🇨🇬",
  },
  CH: {
    code: "CH",
    unicode: "U+1F1E8 U+1F1ED",
    name: "Suisse",
    emoji: "🇨🇭",
  },
  CI: {
    code: "CI",
    unicode: "U+1F1E8 U+1F1EE",
    name: "Côte d’Ivoire",
    emoji: "🇨🇮",
  },
  CK: {
    code: "CK",
    unicode: "U+1F1E8 U+1F1F0",
    name: "Îles Cook",
    emoji: "🇨🇰",
  },
  CL: {
    code: "CL",
    unicode: "U+1F1E8 U+1F1F1",
    name: "Chili",
    emoji: "🇨🇱",
  },
  CM: {
    code: "CM",
    unicode: "U+1F1E8 U+1F1F2",
    name: "Cameroun",
    emoji: "🇨🇲",
  },
  CN: {
    code: "CN",
    unicode: "U+1F1E8 U+1F1F3",
    name: "Chine",
    emoji: "🇨🇳",
  },
  CO: {
    code: "CO",
    unicode: "U+1F1E8 U+1F1F4",
    name: "Colombie",
    emoji: "🇨🇴",
  },
  CP: {
    code: "CP",
    unicode: "U+1F1E8 U+1F1F5",
    name: "Île de Clipperton",
    emoji: "🇨🇵",
  },
  CR: {
    code: "CR",
    unicode: "U+1F1E8 U+1F1F7",
    name: "Costa Rica",
    emoji: "🇨🇷",
  },
  CU: {
    code: "CU",
    unicode: "U+1F1E8 U+1F1FA",
    name: "Cuba",
    emoji: "🇨🇺",
  },
  CV: {
    code: "CV",
    unicode: "U+1F1E8 U+1F1FB",
    name: "Cap-Vert",
    emoji: "🇨🇻",
  },
  CW: {
    code: "CW",
    unicode: "U+1F1E8 U+1F1FC",
    name: "Curaçao",
    emoji: "🇨🇼",
  },
  CX: {
    code: "CX",
    unicode: "U+1F1E8 U+1F1FD",
    name: "Île Christmas",
    emoji: "🇨🇽",
  },
  CY: {
    code: "CY",
    unicode: "U+1F1E8 U+1F1FE",
    name: "Chypre",
    emoji: "🇨🇾",
  },
  CZ: {
    code: "CZ",
    unicode: "U+1F1E8 U+1F1FF",
    name: "Tchéquie",
    emoji: "🇨🇿",
  },
  DE: {
    code: "DE",
    unicode: "U+1F1E9 U+1F1EA",
    name: "Allemagne",
    emoji: "🇩🇪",
  },
  DG: {
    code: "DG",
    unicode: "U+1F1E9 U+1F1EC",
    name: "Diego Garcia",
    emoji: "🇩🇬",
  },
  DJ: {
    code: "DJ",
    unicode: "U+1F1E9 U+1F1EF",
    name: "Djibouti",
    emoji: "🇩🇯",
  },
  DK: {
    code: "DK",
    unicode: "U+1F1E9 U+1F1F0",
    name: "Danemark",
    emoji: "🇩🇰",
  },
  DM: {
    code: "DM",
    unicode: "U+1F1E9 U+1F1F2",
    name: "Dominique",
    emoji: "🇩🇲",
  },
  DO: {
    code: "DO",
    unicode: "U+1F1E9 U+1F1F4",
    name: "République dominicaine",
    emoji: "🇩🇴",
  },
  DZ: {
    code: "DZ",
    unicode: "U+1F1E9 U+1F1FF",
    name: "Algérie",
    emoji: "🇩🇿",
  },
  EA: {
    code: "EA",
    unicode: "U+1F1EA U+1F1E6",
    name: "Ceuta & Melilla",
    emoji: "🇪🇦",
  },
  EC: {
    code: "EC",
    unicode: "U+1F1EA U+1F1E8",
    name: "Équateur",
    emoji: "🇪🇨",
  },
  EE: {
    code: "EE",
    unicode: "U+1F1EA U+1F1EA",
    name: "Estonie",
    emoji: "🇪🇪",
  },
  EG: {
    code: "EG",
    unicode: "U+1F1EA U+1F1EC",
    name: "Égypte",
    emoji: "🇪🇬",
  },
  EH: {
    code: "EH",
    unicode: "U+1F1EA U+1F1ED",
    name: "Sahara occidental",
    emoji: "🇪🇭",
  },
  ER: {
    code: "ER",
    unicode: "U+1F1EA U+1F1F7",
    name: "Érythrée",
    emoji: "🇪🇷",
  },
  ES: {
    code: "ES",
    unicode: "U+1F1EA U+1F1F8",
    name: "Espagne",
    emoji: "🇪🇸",
  },
  ET: {
    code: "ET",
    unicode: "U+1F1EA U+1F1F9",
    name: "Éthiopie",
    emoji: "🇪🇹",
  },
  EU: {
    code: "EU",
    unicode: "U+1F1EA U+1F1FA",
    name: "Union européenne",
    emoji: "🇪🇺",
  },
  FI: {
    code: "FI",
    unicode: "U+1F1EB U+1F1EE",
    name: "Finlande",
    emoji: "🇫🇮",
  },
  FJ: {
    code: "FJ",
    unicode: "U+1F1EB U+1F1EF",
    name: "Fidji",
    emoji: "🇫🇯",
  },
  FK: {
    code: "FK",
    unicode: "U+1F1EB U+1F1F0",
    name: "Îles Falkland",
    emoji: "🇫🇰",
  },
  FM: {
    code: "FM",
    unicode: "U+1F1EB U+1F1F2",
    name: "Micronésie",
    emoji: "🇫🇲",
  },
  FO: {
    code: "FO",
    unicode: "U+1F1EB U+1F1F4",
    name: "Îles Féroé",
    emoji: "🇫🇴",
  },
  FR: {
    code: "FR",
    unicode: "U+1F1EB U+1F1F7",
    name: "France",
    emoji: "🇫🇷",
  },
  GA: {
    code: "GA",
    unicode: "U+1F1EC U+1F1E6",
    name: "Gabon",
    emoji: "🇬🇦",
  },
  GB: {
    code: "GB",
    unicode: "U+1F1EC U+1F1E7",
    name: "Royaume-Uni",
    emoji: "🇬🇧",
  },
  GD: {
    code: "GD",
    unicode: "U+1F1EC U+1F1E9",
    name: "Grenade",
    emoji: "🇬🇩",
  },
  GE: {
    code: "GE",
    unicode: "U+1F1EC U+1F1EA",
    name: "Géorgie",
    emoji: "🇬🇪",
  },
  GF: {
    code: "GF",
    unicode: "U+1F1EC U+1F1EB",
    name: "Guyane française",
    emoji: "🇬🇫",
  },
  GG: {
    code: "GG",
    unicode: "U+1F1EC U+1F1EC",
    name: "Guernesey",
    emoji: "🇬🇬",
  },
  GH: {
    code: "GH",
    unicode: "U+1F1EC U+1F1ED",
    name: "Ghana",
    emoji: "🇬🇭",
  },
  GI: {
    code: "GI",
    unicode: "U+1F1EC U+1F1EE",
    name: "Gibraltar",
    emoji: "🇬🇮",
  },
  GL: {
    code: "GL",
    unicode: "U+1F1EC U+1F1F1",
    name: "Groenland",
    emoji: "🇬🇱",
  },
  GM: {
    code: "GM",
    unicode: "U+1F1EC U+1F1F2",
    name: "Gambie",
    emoji: "🇬🇲",
  },
  GN: {
    code: "GN",
    unicode: "U+1F1EC U+1F1F3",
    name: "Guinée",
    emoji: "🇬🇳",
  },
  GP: {
    code: "GP",
    unicode: "U+1F1EC U+1F1F5",
    name: "Guadeloupe",
    emoji: "🇬🇵",
  },
  GQ: {
    code: "GQ",
    unicode: "U+1F1EC U+1F1F6",
    name: "Guinée équatoriale",
    emoji: "🇬🇶",
  },
  GR: {
    code: "GR",
    unicode: "U+1F1EC U+1F1F7",
    name: "Grèce",
    emoji: "🇬🇷",
  },
  GS: {
    code: "GS",
    unicode: "U+1F1EC U+1F1F8",
    name: "Géorgie du Sud et les îles Sandwich du Sud",
    emoji: "🇬🇸",
  },
  GT: {
    code: "GT",
    unicode: "U+1F1EC U+1F1F9",
    name: "Guatemala",
    emoji: "🇬🇹",
  },
  GU: {
    code: "GU",
    unicode: "U+1F1EC U+1F1FA",
    name: "Guam",
    emoji: "🇬🇺",
  },
  GW: {
    code: "GW",
    unicode: "U+1F1EC U+1F1FC",
    name: "Guinée-Bissau",
    emoji: "🇬🇼",
  },
  GY: {
    code: "GY",
    unicode: "U+1F1EC U+1F1FE",
    name: "Guyana",
    emoji: "🇬🇾",
  },
  HK: {
    code: "HK",
    unicode: "U+1F1ED U+1F1F0",
    name: "Hong Kong",
    emoji: "🇭🇰",
  },
  HM: {
    code: "HM",
    unicode: "U+1F1ED U+1F1F2",
    name: "Îles Heard et McDonald",
    emoji: "🇭🇲",
  },
  HN: {
    code: "HN",
    unicode: "U+1F1ED U+1F1F3",
    name: "Honduras",
    emoji: "🇭🇳",
  },
  HR: {
    code: "HR",
    unicode: "U+1F1ED U+1F1F7",
    name: "Croatie",
    emoji: "🇭🇷",
  },
  HT: {
    code: "HT",
    unicode: "U+1F1ED U+1F1F9",
    name: "Haïti",
    emoji: "🇭🇹",
  },
  HU: {
    code: "HU",
    unicode: "U+1F1ED U+1F1FA",
    name: "Hongrie",
    emoji: "🇭🇺",
  },
  IC: {
    code: "IC",
    unicode: "U+1F1EE U+1F1E8",
    name: "Îles Canaries",
    emoji: "🇮🇨",
  },
  ID: {
    code: "ID",
    unicode: "U+1F1EE U+1F1E9",
    name: "Indonésie",
    emoji: "🇮🇩",
  },
  IE: {
    code: "IE",
    unicode: "U+1F1EE U+1F1EA",
    name: "Irlande",
    emoji: "🇮🇪",
  },
  IL: {
    code: "IL",
    unicode: "U+1F1EE U+1F1F1",
    name: "Israël",
    emoji: "🇮🇱",
  },
  IM: {
    code: "IM",
    unicode: "U+1F1EE U+1F1F2",
    name: "Île de Man",
    emoji: "🇮🇲",
  },
  IN: {
    code: "IN",
    unicode: "U+1F1EE U+1F1F3",
    name: "Inde",
    emoji: "🇮🇳",
  },
  IO: {
    code: "IO",
    unicode: "U+1F1EE U+1F1F4",
    name: "Territoire britannique de l'océan Indien",
    emoji: "🇮🇴",
  },
  IQ: {
    code: "IQ",
    unicode: "U+1F1EE U+1F1F6",
    name: "Irak",
    emoji: "🇮🇶",
  },
  IR: {
    code: "IR",
    unicode: "U+1F1EE U+1F1F7",
    name: "Iran",
    emoji: "🇮🇷",
  },
  IS: {
    code: "IS",
    unicode: "U+1F1EE U+1F1F8",
    name: "Islande",
    emoji: "🇮🇸",
  },
  IT: {
    code: "IT",
    unicode: "U+1F1EE U+1F1F9",
    name: "Italie",
    emoji: "🇮🇹",
  },
  JE: {
    code: "JE",
    unicode: "U+1F1EF U+1F1EA",
    name: "Jersey",
    emoji: "🇯🇪",
  },
  JM: {
    code: "JM",
    unicode: "U+1F1EF U+1F1F2",
    name: "Jamaïque",
    emoji: "🇯🇲",
  },
  JO: {
    code: "JO",
    unicode: "U+1F1EF U+1F1F4",
    name: "Jordanie",
    emoji: "🇯🇴",
  },
  JP: {
    code: "JP",
    unicode: "U+1F1EF U+1F1F5",
    name: "Japon",
    emoji: "🇯🇵",
  },
  KE: {
    code: "KE",
    unicode: "U+1F1F0 U+1F1EA",
    name: "Kenya",
    emoji: "🇰🇪",
  },
  KG: {
    code: "KG",
    unicode: "U+1F1F0 U+1F1EC",
    name: "Kirghizistan",
    emoji: "🇰🇬",
  },
  KH: {
    code: "KH",
    unicode: "U+1F1F0 U+1F1ED",
    name: "Cambodge",
    emoji: "🇰🇭",
  },
  KI: {
    code: "KI",
    unicode: "U+1F1F0 U+1F1EE",
    name: "Kiribati",
    emoji: "🇰🇮",
  },
  KM: {
    code: "KM",
    unicode: "U+1F1F0 U+1F1F2",
    name: "Comores",
    emoji: "🇰🇲",
  },
  KN: {
    code: "KN",
    unicode: "U+1F1F0 U+1F1F3",
    name: "Saint-Christophe-et-Niévès",
    emoji: "🇰🇳",
  },
  KP: {
    code: "KP",
    unicode: "U+1F1F0 U+1F1F5",
    name: "Corée du Nord",
    emoji: "🇰🇵",
  },
  KR: {
    code: "KR",
    unicode: "U+1F1F0 U+1F1F7",
    name: "Corée du Sud",
    emoji: "🇰🇷",
  },
  KW: {
    code: "KW",
    unicode: "U+1F1F0 U+1F1FC",
    name: "Koweït",
    emoji: "🇰🇼",
  },
  KY: {
    code: "KY",
    unicode: "U+1F1F0 U+1F1FE",
    name: "Îles Caïmanes",
    emoji: "🇰🇾",
  },
  KZ: {
    code: "KZ",
    unicode: "U+1F1F0 U+1F1FF",
    name: "Kazakhstan",
    emoji: "🇰🇿",
  },
  LA: {
    code: "LA",
    unicode: "U+1F1F1 U+1F1E6",
    name: "Laos",
    emoji: "🇱🇦",
  },
  LB: {
    code: "LB",
    unicode: "U+1F1F1 U+1F1E7",
    name: "Liban",
    emoji: "🇱🇧",
  },
  LC: {
    code: "LC",
    unicode: "U+1F1F1 U+1F1E8",
    name: "Sainte-Lucie",
    emoji: "🇱🇨",
  },
  LI: {
    code: "LI",
    unicode: "U+1F1F1 U+1F1EE",
    name: "Liechtenstein",
    emoji: "🇱🇮",
  },
  LK: {
    code: "LK",
    unicode: "U+1F1F1 U+1F1F0",
    name: "Sri Lanka",
    emoji: "🇱🇰",
  },
  LR: {
    code: "LR",
    unicode: "U+1F1F1 U+1F1F7",
    name: "Libéria",
    emoji: "🇱🇷",
  },
  LS: {
    code: "LS",
    unicode: "U+1F1F1 U+1F1F8",
    name: "Lesotho",
    emoji: "🇱🇸",
  },
  LT: {
    code: "LT",
    unicode: "U+1F1F1 U+1F1F9",
    name: "Lituanie",
    emoji: "🇱🇹",
  },
  LU: {
    code: "LU",
    unicode: "U+1F1F1 U+1F1FA",
    name: "Luxembourg",
    emoji: "🇱🇺",
  },
  LV: {
    code: "LV",
    unicode: "U+1F1F1 U+1F1FB",
    name: "Lettonie",
    emoji: "🇱🇻",
  },
  LY: {
    code: "LY",
    unicode: "U+1F1F1 U+1F1FE",
    name: "Libye",
    emoji: "🇱🇾",
  },
  MA: {
    code: "MA",
    unicode: "U+1F1F2 U+1F1E6",
    name: "Maroc",
    emoji: "🇲🇦",
  },
  MC: {
    code: "MC",
    unicode: "U+1F1F2 U+1F1E8",
    name: "Monaco",
    emoji: "🇲🇨",
  },
  MD: {
    code: "MD",
    unicode: "U+1F1F2 U+1F1E9",
    name: "Moldavie",
    emoji: "🇲🇩",
  },
  ME: {
    code: "ME",
    unicode: "U+1F1F2 U+1F1EA",
    name: "Monténégro",
    emoji: "🇲🇪",
  },
  MF: {
    code: "MF",
    unicode: "U+1F1F2 U+1F1EB",
    name: "Saint-Martin",
    emoji: "🇲🇫",
  },
  MG: {
    code: "MG",
    unicode: "U+1F1F2 U+1F1EC",
    name: "Madagascar",
    emoji: "🇲🇬",
  },
  MH: {
    code: "MH",
    unicode: "U+1F1F2 U+1F1ED",
    name: "Îles Marshall",
    emoji: "🇲🇭",
  },
  MK: {
    code: "MK",
    unicode: "U+1F1F2 U+1F1F0",
    name: "Macédoine",
    emoji: "🇲🇰",
  },
  ML: {
    code: "ML",
    unicode: "U+1F1F2 U+1F1F1",
    name: "Mali",
    emoji: "🇲🇱",
  },
  MM: {
    code: "MM",
    unicode: "U+1F1F2 U+1F1F2",
    name: "Myanmar (Birmanie)",
    emoji: "🇲🇲",
  },
  MN: {
    code: "MN",
    unicode: "U+1F1F2 U+1F1F3",
    name: "Mongolie",
    emoji: "🇲🇳",
  },
  MO: {
    code: "MO",
    unicode: "U+1F1F2 U+1F1F4",
    name: "Macao RAS de Chine",
    emoji: "🇲🇴",
  },
  MP: {
    code: "MP",
    unicode: "U+1F1F2 U+1F1F5",
    name: "Îles Mariannes du Nord",
    emoji: "🇲🇵",
  },
  MQ: {
    code: "MQ",
    unicode: "U+1F1F2 U+1F1F6",
    name: "Martinique",
    emoji: "🇲🇶",
  },
  MR: {
    code: "MR",
    unicode: "U+1F1F2 U+1F1F7",
    name: "Mauritanie",
    emoji: "🇲🇷",
  },
  MS: {
    code: "MS",
    unicode: "U+1F1F2 U+1F1F8",
    name: "Montserrat",
    emoji: "🇲🇸",
  },
  MT: {
    code: "MT",
    unicode: "U+1F1F2 U+1F1F9",
    name: "Malte",
    emoji: "🇲🇹",
  },
  MU: {
    code: "MU",
    unicode: "U+1F1F2 U+1F1FA",
    name: "Maurice",
    emoji: "🇲🇺",
  },
  MV: {
    code: "MV",
    unicode: "U+1F1F2 U+1F1FB",
    name: "Maldives",
    emoji: "🇲🇻",
  },
  MW: {
    code: "MW",
    unicode: "U+1F1F2 U+1F1FC",
    name: "Malawi",
    emoji: "🇲🇼",
  },
  MX: {
    code: "MX",
    unicode: "U+1F1F2 U+1F1FD",
    name: "Mexique",
    emoji: "🇲🇽",
  },
  MY: {
    code: "MY",
    unicode: "U+1F1F2 U+1F1FE",
    name: "Malaisie",
    emoji: "🇲🇾",
  },
  MZ: {
    code: "MZ",
    unicode: "U+1F1F2 U+1F1FF",
    name: "Mozambique",
    emoji: "🇲🇿",
  },
  NA: {
    code: "NA",
    unicode: "U+1F1F3 U+1F1E6",
    name: "Namibie",
    emoji: "🇳🇦",
  },
  NC: {
    code: "NC",
    unicode: "U+1F1F3 U+1F1E8",
    name: "Nouvelle-Calédonie",
    emoji: "🇳🇨",
  },
  NE: {
    code: "NE",
    unicode: "U+1F1F3 U+1F1EA",
    name: "Niger",
    emoji: "🇳🇪",
  },
  NF: {
    code: "NF",
    unicode: "U+1F1F3 U+1F1EB",
    name: "Île Norfolk",
    emoji: "🇳🇫",
  },
  NG: {
    code: "NG",
    unicode: "U+1F1F3 U+1F1EC",
    name: "Nigéria",
    emoji: "🇳🇬",
  },
  NI: {
    code: "NI",
    unicode: "U+1F1F3 U+1F1EE",
    name: "Nicaragua",
    emoji: "🇳🇮",
  },
  NL: {
    code: "NL",
    unicode: "U+1F1F3 U+1F1F1",
    name: "Pays-Bas",
    emoji: "🇳🇱",
  },
  NO: {
    code: "NO",
    unicode: "U+1F1F3 U+1F1F4",
    name: "Norvège",
    emoji: "🇳🇴",
  },
  NP: {
    code: "NP",
    unicode: "U+1F1F3 U+1F1F5",
    name: "Népal",
    emoji: "🇳🇵",
  },
  NR: {
    code: "NR",
    unicode: "U+1F1F3 U+1F1F7",
    name: "Nauru",
    emoji: "🇳🇷",
  },
  NU: {
    code: "NU",
    unicode: "U+1F1F3 U+1F1FA",
    name: "Nioué",
    emoji: "🇳🇺",
  },
  NZ: {
    code: "NZ",
    unicode: "U+1F1F3 U+1F1FF",
    name: "Nouvelle-Zélande",
    emoji: "🇳🇿",
  },
  OM: {
    code: "OM",
    unicode: "U+1F1F4 U+1F1F2",
    name: "Oman",
    emoji: "🇴🇲",
  },
  PA: {
    code: "PA",
    unicode: "U+1F1F5 U+1F1E6",
    name: "Panama",
    emoji: "🇵🇦",
  },
  PE: {
    code: "PE",
    unicode: "U+1F1F5 U+1F1EA",
    name: "Pérou",
    emoji: "🇵🇪",
  },
  PF: {
    code: "PF",
    unicode: "U+1F1F5 U+1F1EB",
    name: "Polynésie française",
    emoji: "🇵🇫",
  },
  PG: {
    code: "PG",
    unicode: "U+1F1F5 U+1F1EC",
    name: "Papouasie-Nouvelle-Guinée",
    emoji: "🇵🇬",
  },
  PH: {
    code: "PH",
    unicode: "U+1F1F5 U+1F1ED",
    name: "Philippines",
    emoji: "🇵🇭",
  },
  PK: {
    code: "PK",
    unicode: "U+1F1F5 U+1F1F0",
    name: "Pakistan",
    emoji: "🇵🇰",
  },
  PL: {
    code: "PL",
    unicode: "U+1F1F5 U+1F1F1",
    name: "Pologne",
    emoji: "🇵🇱",
  },
  PM: {
    code: "PM",
    unicode: "U+1F1F5 U+1F1F2",
    name: "Saint-Pierre-et-Miquelon",
    emoji: "🇵🇲",
  },
  PN: {
    code: "PN",
    unicode: "U+1F1F5 U+1F1F3",
    name: "Îles Pitcairn",
    emoji: "🇵🇳",
  },
  PR: {
    code: "PR",
    unicode: "U+1F1F5 U+1F1F7",
    name: "Porto Rico",
    emoji: "🇵🇷",
  },
  PS: {
    code: "PS",
    unicode: "U+1F1F5 U+1F1F8",
    name: "Territoires palestiniens",
    emoji: "🇵🇸",
  },
  PT: {
    code: "PT",
    unicode: "U+1F1F5 U+1F1F9",
    name: "Portugal",
    emoji: "🇵🇹",
  },
  PW: {
    code: "PW",
    unicode: "U+1F1F5 U+1F1FC",
    name: "Palaos",
    emoji: "🇵🇼",
  },
  PY: {
    code: "PY",
    unicode: "U+1F1F5 U+1F1FE",
    name: "Paraguay",
    emoji: "🇵🇾",
  },
  QA: {
    code: "QA",
    unicode: "U+1F1F6 U+1F1E6",
    name: "Qatar",
    emoji: "🇶🇦",
  },
  RE: {
    code: "RE",
    unicode: "U+1F1F7 U+1F1EA",
    name: "La Réunion",
    emoji: "🇷🇪",
  },
  RO: {
    code: "RO",
    unicode: "U+1F1F7 U+1F1F4",
    name: "Roumanie",
    emoji: "🇷🇴",
  },
  RS: {
    code: "RS",
    unicode: "U+1F1F7 U+1F1F8",
    name: "Serbie",
    emoji: "🇷🇸",
  },
  RU: {
    code: "RU",
    unicode: "U+1F1F7 U+1F1FA",
    name: "Russie",
    emoji: "🇷🇺",
  },
  RW: {
    code: "RW",
    unicode: "U+1F1F7 U+1F1FC",
    name: "Rwanda",
    emoji: "🇷🇼",
  },
  SA: {
    code: "SA",
    unicode: "U+1F1F8 U+1F1E6",
    name: "Arabie saoudite",
    emoji: "🇸🇦",
  },
  SB: {
    code: "SB",
    unicode: "U+1F1F8 U+1F1E7",
    name: "Îles Salomon",
    emoji: "🇸🇧",
  },
  SC: {
    code: "SC",
    unicode: "U+1F1F8 U+1F1E8",
    name: "Seychelles",
    emoji: "🇸🇨",
  },
  SD: {
    code: "SD",
    unicode: "U+1F1F8 U+1F1E9",
    name: "Soudan",
    emoji: "🇸🇩",
  },
  SE: {
    code: "SE",
    unicode: "U+1F1F8 U+1F1EA",
    name: "Suède",
    emoji: "🇸🇪",
  },
  SG: {
    code: "SG",
    unicode: "U+1F1F8 U+1F1EC",
    name: "Singapour",
    emoji: "🇸🇬",
  },
  SH: {
    code: "SH",
    unicode: "U+1F1F8 U+1F1ED",
    name: "Sainte-Hélène",
    emoji: "🇸🇭",
  },
  SI: {
    code: "SI",
    unicode: "U+1F1F8 U+1F1EE",
    name: "Slovénie",
    emoji: "🇸🇮",
  },
  SJ: {
    code: "SJ",
    unicode: "U+1F1F8 U+1F1EF",
    name: "Svalbard et Jan Mayen",
    emoji: "🇸🇯",
  },
  SK: {
    code: "SK",
    unicode: "U+1F1F8 U+1F1F0",
    name: "Slovaquie",
    emoji: "🇸🇰",
  },
  SL: {
    code: "SL",
    unicode: "U+1F1F8 U+1F1F1",
    name: "Sierra Leone",
    emoji: "🇸🇱",
  },
  SM: {
    code: "SM",
    unicode: "U+1F1F8 U+1F1F2",
    name: "Saint-Marin",
    emoji: "🇸🇲",
  },
  SN: {
    code: "SN",
    unicode: "U+1F1F8 U+1F1F3",
    name: "Sénégal",
    emoji: "🇸🇳",
  },
  SO: {
    code: "SO",
    unicode: "U+1F1F8 U+1F1F4",
    name: "Somalie",
    emoji: "🇸🇴",
  },
  SR: {
    code: "SR",
    unicode: "U+1F1F8 U+1F1F7",
    name: "Suriname",
    emoji: "🇸🇷",
  },
  SS: {
    code: "SS",
    unicode: "U+1F1F8 U+1F1F8",
    name: "Soudan du Sud",
    emoji: "🇸🇸",
  },
  ST: {
    code: "ST",
    unicode: "U+1F1F8 U+1F1F9",
    name: "São Tomé-et-Principe",
    emoji: "🇸🇹",
  },
  SV: {
    code: "SV",
    unicode: "U+1F1F8 U+1F1FB",
    name: "El Salvador",
    emoji: "🇸🇻",
  },
  SX: {
    code: "SX",
    unicode: "U+1F1F8 U+1F1FD",
    name: "Saint-Martin",
    emoji: "🇸🇽",
  },
  SY: {
    code: "SY",
    unicode: "U+1F1F8 U+1F1FE",
    name: "Syrie",
    emoji: "🇸🇾",
  },
  SZ: {
    code: "SZ",
    unicode: "U+1F1F8 U+1F1FF",
    name: "Eswatini",
    emoji: "🇸🇿",
  },
  TA: {
    code: "TA",
    unicode: "U+1F1F9 U+1F1E6",
    name: "Tristan da Cunha",
    emoji: "🇹🇦",
  },
  TC: {
    code: "TC",
    unicode: "U+1F1F9 U+1F1E8",
    name: "Îles Turques et Caïques",
    emoji: "🇹🇨",
  },
  TD: {
    code: "TD",
    unicode: "U+1F1F9 U+1F1E9",
    name: "Tchad",
    emoji: "🇹🇩",
  },
  TF: {
    code: "TF",
    unicode: "U+1F1F9 U+1F1EB",
    name: "Territoires austraux et antarctiques français",
    emoji: "🇹🇫",
  },
  TG: {
    code: "TG",
    unicode: "U+1F1F9 U+1F1EC",
    name: "Togo",
    emoji: "🇹🇬",
  },
  TH: {
    code: "TH",
    unicode: "U+1F1F9 U+1F1ED",
    name: "Thaïlande",
    emoji: "🇹🇭",
  },
  TJ: {
    code: "TJ",
    unicode: "U+1F1F9 U+1F1EF",
    name: "Tadjikistan",
    emoji: "🇹🇯",
  },
  TK: {
    code: "TK",
    unicode: "U+1F1F9 U+1F1F0",
    name: "Tokelau",
    emoji: "🇹🇰",
  },
  TL: {
    code: "TL",
    unicode: "U+1F1F9 U+1F1F1",
    name: "Timor oriental",
    emoji: "🇹🇱",
  },
  TM: {
    code: "TM",
    unicode: "U+1F1F9 U+1F1F2",
    name: "Turkménistan",
    emoji: "🇹🇲",
  },
  TN: {
    code: "TN",
    unicode: "U+1F1F9 U+1F1F3",
    name: "Tunisie",
    emoji: "🇹🇳",
  },
  TO: {
    code: "TO",
    unicode: "U+1F1F9 U+1F1F4",
    name: "Tonga",
    emoji: "🇹🇴",
  },
  TR: {
    code: "TR",
    unicode: "U+1F1F9 U+1F1F7",
    name: "Turquie",
    emoji: "🇹🇷",
  },
  TT: {
    code: "TT",
    unicode: "U+1F1F9 U+1F1F9",
    name: "Trinité-et-Tobago",
    emoji: "🇹🇹",
  },
  TV: {
    code: "TV",
    unicode: "U+1F1F9 U+1F1FB",
    name: "Tuvalu",
    emoji: "🇹🇻",
  },
  TW: {
    code: "TW",
    unicode: "U+1F1F9 U+1F1FC",
    name: "Taïwan",
    emoji: "🇹🇼",
  },
  TZ: {
    code: "TZ",
    unicode: "U+1F1F9 U+1F1FF",
    name: "Tanzanie",
    emoji: "🇹🇿",
  },
  UA: {
    code: "UA",
    unicode: "U+1F1FA U+1F1E6",
    name: "Ukraine",
    emoji: "🇺🇦",
  },
  UG: {
    code: "UG",
    unicode: "U+1F1FA U+1F1EC",
    name: "Ouganda",
    emoji: "🇺🇬",
  },
  UM: {
    code: "UM",
    unicode: "U+1F1FA U+1F1F2",
    name: "Îles mineures éloignées des États-Unis",
    emoji: "🇺🇲",
  },
  UN: {
    code: "UN",
    unicode: "U+1F1FA U+1F1F3",
    name: "Organisation des Nations unies",
    emoji: "🇺🇳",
  },
  US: {
    code: "US",
    unicode: "U+1F1FA U+1F1F8",
    name: "États-Unis",
    emoji: "🇺🇸",
  },
  UY: {
    code: "UY",
    unicode: "U+1F1FA U+1F1FE",
    name: "Uruguay",
    emoji: "🇺🇾",
  },
  UZ: {
    code: "UZ",
    unicode: "U+1F1FA U+1F1FF",
    name: "Ouzbékistan",
    emoji: "🇺🇿",
  },
  VA: {
    code: "VA",
    unicode: "U+1F1FB U+1F1E6",
    name: "Vatican",
    emoji: "🇻🇦",
  },
  VC: {
    code: "VC",
    unicode: "U+1F1FB U+1F1E8",
    name: "Saint-Vincent-et-les-Grenadines",
    emoji: "🇻🇨",
  },
  VE: {
    code: "VE",
    unicode: "U+1F1FB U+1F1EA",
    name: "Venezuela",
    emoji: "🇻🇪",
  },
  VG: {
    code: "VG",
    unicode: "U+1F1FB U+1F1EC",
    name: "Îles Vierges britanniques",
    emoji: "🇻🇬",
  },
  VI: {
    code: "VI",
    unicode: "U+1F1FB U+1F1EE",
    name: "Îles Vierges des États-Unis",
    emoji: "🇻🇮",
  },
  VN: {
    code: "VN",
    unicode: "U+1F1FB U+1F1F3",
    name: "Vietnam",
    emoji: "🇻🇳",
  },
  VU: {
    code: "VU",
    unicode: "U+1F1FB U+1F1FA",
    name: "Vanuatu",
    emoji: "🇻🇺",
  },
  WF: {
    code: "WF",
    unicode: "U+1F1FC U+1F1EB",
    name: "Wallis-et-Futuna",
    emoji: "🇼🇫",
  },
  WS: {
    code: "WS",
    unicode: "U+1F1FC U+1F1F8",
    name: "Samoa",
    emoji: "🇼🇸",
  },
  XK: {
    code: "XK",
    unicode: "U+1F1FD U+1F1F0",
    name: "Kosovo",
    emoji: "🇽🇰",
  },
  YE: {
    code: "YE",
    unicode: "U+1F1FE U+1F1EA",
    name: "Yémen",
    emoji: "🇾🇪",
  },
  YT: {
    code: "YT",
    unicode: "U+1F1FE U+1F1F9",
    name: "Mayotte",
    emoji: "🇾🇹",
  },
  ZA: {
    code: "ZA",
    unicode: "U+1F1FF U+1F1E6",
    name: "Afrique du Sud",
    emoji: "🇿🇦",
  },
  ZM: {
    code: "ZM",
    unicode: "U+1F1FF U+1F1F2",
    name: "Zambie",
    emoji: "🇿🇲",
  },
  ZW: {
    code: "ZW",
    unicode: "U+1F1FF U+1F1FC",
    name: "Zimbabwe",
    emoji: "🇿🇼",
  },
} as const;

export type CountryCode = keyof typeof countries;
