export const pricingPlans = [
  {
    plan: "Starter",
    price: "€7.500",
    duration: "Mois",
    description: "Ideal for small projects and individuals.",
    features: [
      { text: "500 Submissions", included: true },
      { text: "Up to 5 locations", included: true },
      { text: "1 round of review", included: true },
      { text: "10 Questions per survey", included: true },
      { text: "3 Filters", included: true },
      { text: "Users access", included: true },
      { text: "Powerpoint reporting", included: false },
      { text: "Access to survey templates", included: false },
      { text: "Import survey forms", included: false },
      { text: "All data (text, image, video, GPS)", included: false },
      { text: "Interactive dashboards", included: false },
      { text: "Personalized insights", included: false },
      { text: "Dynamic Filters (2SQL)", included: false },
      { text: "Dashboard collaboration", included: false },
      { text: "Raw data import", included: false },
      { text: "Digital report with summaries", included: false },
      { text: "Multicurrency", included: false },
      { text: "Multilanguage", included: false },
      { text: "API access", included: false },
      { text: "AI + Human QC", included: false },
    ],
  },
  {
    plan: "Growth",
    price: "€13.500",
    duration: "Mois",
    description: "Perfect for growing businesses needing more features.",
    features: [
      { text: "1000 Submissions", included: true },
      { text: "Up to 10 locations", included: true },
      { text: "2 rounds of review", included: true },
      { text: "15 Questions per survey", included: true },
      { text: "5 Filters", included: true },
      { text: "Users access", included: true },
      { text: "Powerpoint reporting", included: true },
      { text: "Access to survey templates", included: true },
      { text: "Import survey forms", included: true },
      { text: "All data (text, image, video, GPS)", included: true },
      { text: "Interactive dashboards", included: true },
      { text: "Personalized insights", included: true },
      { text: "Dynamic Filters (2SQL)", included: true },
      { text: "Dashboard collaboration", included: false },
      { text: "Raw data import", included: false },
      { text: "Digital report with summaries", included: false },
      { text: "Multicurrency", included: false },
      { text: "Multilanguage", included: false },
      { text: "API access", included: false },
      { text: "AI + Human QC", included: false },
    ],
    isPopular: true,
  },
  {
    plan: "Business",
    price: "€25.000",
    duration: "Mois",
    description: "For established businesses with advanced needs.",
    features: [
      { text: "2000 Submissions", included: true },
      { text: "Unlimited locations", included: true },
      { text: "Unlimited review rounds", included: true },
      { text: "Unlimited Questions per survey", included: true },
      { text: "Unlimited Filters", included: true },
      { text: "Users access", included: true },
      { text: "Powerpoint reporting", included: true },
      { text: "Access to survey templates", included: true },
      { text: "Import survey forms", included: true },
      { text: "All data (text, image, video, GPS)", included: true },
      { text: "Interactive dashboards", included: true },
      { text: "Personalized insights", included: true },
      { text: "Dynamic Filters (2SQL)", included: true },
      { text: "Dashboard collaboration", included: true },
      { text: "Raw data import", included: true },
      { text: "Digital report with summaries", included: true },
      { text: "Multicurrency", included: true },
      { text: "Multilanguage", included: true },
      { text: "API access", included: false },
      { text: "AI + Human QC", included: false },
    ],
  },
  {
    plan: "Enterprise",
    price: "Custom",
    duration: "Mois",
    description: "Tailored solutions for large organizations.",
    features: [
      { text: "Unlimited Submissions", included: true },
      { text: "Unlimited locations", included: true },
      { text: "Unlimited review rounds", included: true },
      { text: "Unlimited Questions per survey", included: true },
      { text: "Unlimited Filters", included: true },
      { text: "Users access", included: true },
      { text: "Powerpoint reporting", included: true },
      { text: "Access to survey templates", included: true },
      { text: "Import survey forms", included: true },
      { text: "All data (text, image, video, GPS)", included: true },
      { text: "Interactive dashboards", included: true },
      { text: "Personalized insights", included: true },
      { text: "Dynamic Filters (2SQL)", included: true },
      { text: "Dashboard collaboration", included: true },
      { text: "Raw data import", included: true },
      { text: "Digital report with summaries", included: true },
      { text: "Multicurrency", included: true },
      { text: "Multilanguage", included: true },
      { text: "API access", included: true },
      { text: "AI + Human QC", included: true },
    ],
  },
];
